from .projects_controller import ProjectController
from .user_controller import UserController
from .subs_controller import SubscriptionsCtrl
from .universidad_controller import UniversidadCtrl
from .detallesFinance_controller import DetalleFinanceCtrl
from .financiadores_controller import FinanciadorCtrl
from .evento_ctrl import EventoCtrl